In [ ]:
import numpy as np

In [ ]:
steps=np.array([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6941],[8,7763],[9,8063],[10,9569]])
print(steps)
print('adding 2000')
steps[:,1]+=2000
print(steps)
print("gre")
steps[:,1]>8000
print(steps)

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6941]
 [   8 7763]
 [   9 8063]
 [  10 9569]]
adding 2000
[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8941]
 [    8  9763]
 [    9 10063]
 [   10 11569]]
gre
[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8941]
 [    8  9763]
 [    9 10063]
 [   10 11569]]


In [ ]:
print(steps)

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6941]
 [   8 7763]
 [   9 8063]
 [  10 9569]]
